version: 2.1

executors:
  build:
    parameters:
      go-version:
        type: string
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/d-kuro/go-sandbox

commands:
  go_mod_download:
    steps:
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          name: Save go modules cache
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

jobs:
  build:
    parameters:
      go-version:
        type: string
    executor:
      name: build
      go-version: "1.12"
    steps:
      - checkout
      - go_mod_download
      - run:
          name: Run Tests
          command: go test -race -v ./...

workflows:
  golang-workflow:
    jobs:
      - build:
          go-version: "1.12.4"
